# https://travis-ci.org

before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
- export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
script:
  - qmake -qt=qt5 trianglemesh.pro -r -v
  - qmake -qt=qt5 trianglemesh.pro -r
  - make
